[build]
  command = "npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

# Note: For scheduled notifications, we'll use external cron services
# or manual triggering through the admin interface
# Netlify doesn't support built-in cron jobs for free plans
